services:
  api:
    container_name: chat-app-api
    build:
      context: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db
  db:
    container_name: chat-app-db
    image: postgres:16
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=chat-app
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  pgAdmin:
    image: elestio/pgadmin
    restart: always
    container_name: db-management-container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      # map the host port 8080 with the containers pgAdmin port
      - "8080:80"


volumes:
  postgres-data: